---

resources: "config/resources.yaml"
samples: "config/samples.tsv"
units: "config/units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

trimmer_software: "fastp_pe"

reference:
  fasta: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  fai: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fai"
  dict: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.dict"
  amb: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  pac: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.sa"
  design_intervals: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeloid_v.1.1_padd6_201126.sorted.intervals"
  design_bed: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeloid_v.1.1_padd6_201126.sorted.bed"
  skip_chrs:
    - "chrM"

bed_split:
  container: "docker://hydragenetics/common:0.0.1"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"

bgzip_vcf:
  container: "docker://hydragenetics/common:0.0.1"

decompose:
  container: "docker://gmsuppsala/somatic:develop"

ensemble_vcf:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - mutect2
    - vardict
    - freebayes
  sort_order: "mutect2,vardict,freebayes"

fastp_pe:
   container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

fix_af:
  container: "docker://hydragenetics/common:0.0.1"

freebayes:
  container: "docker://hydragenetics/freebayes:1.3.1"

mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

merge_gvcf:
  container: "docker://hydragenetics/common:0.0.1"

merge_vcf:
  container: "docker://hydragenetics/common:0.0.1"

mosdepth:
  by: ""
  container: "docker://hydragenetics/mosdepth:0.3.2"
  extra: ""

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  config: "config/multiqc.yaml"
  qc_files:
    - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
    - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
    - "qc/fastqc/{sample}_{type}_fastq1_fastqc.zip"
    - "qc/fastqc/{sample}_{type}_fastq2_fastqc.zip"
    - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
    - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
    - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
    - "prealignment/fastp_pe/{sample}_{flowcell}_{lane}_{type}.json"

mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

normalize:
  container: "docker://gmsuppsala/somatic:develop"

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_gc_bias_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_multiple_metrics:
  container: "docker://hydragenetics/picard:2.25.0"
  output_ext:
    - "gc_bias.pdf"

samtools_index:
  container: "docker://hydragenetics/common:0.0.1"

sort_vcf:
  container: "docker://hydragenetics/common:0.0.1"

tabix_vcf:
  container: "docker://hydragenetics/common:0.0.1"

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3"
