---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 1024
  mem_per_cpu: 3072
  partition: low

bwa_mem:
  threads: 20
  time: "24:00:00"

fastp_pe:
  threads: 5

fastqc:
  threads: 10
  time: "02:00:00"
